### ISSUE TITLE
您好,运行报错,能帮忙看下吗？谢谢!

### ISSUE THREAD

**Issue by liuxinxin1** [r00t1900/tencent-edu-wrapper#5]
F:\test\tencent-edu-wrapper-master\tencent-edu-wrapper-master>python wrapper_cli.py -h
Traceback (most recent call last):
  File "wrapper_cli.py", line 6, in <module>
    from tencent_edu import wrapper
  File "F:\test\tencent-edu-wrapper-master\tencent-edu-wrapper-master\tencent_edu.py", line 10, in <m
    from pyexcel_xls import save_data
ModuleNotFoundError: No module named 'pyexcel_xls'

**Comment by hochenchong** [comment]
缺少模块，使用命令：`pip install -i https://pypi.douban.com/simple pyexcel_xls`
安装一下 pyexcel_xls 模块即可
